/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.carrito.views;

import ec.edu.ups.carrito.models.controller.ProductoController;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author katherine
 */
public class BuscarProducto extends javax.swing.JInternalFrame {
       private ProductoController productoController;
    public BuscarProducto(ProductoController productoController) {
        initComponents();
        this.productoController = productoController;
    }
     public BuscarProducto() {
        initComponents();
    }

    public JTextField getTxtmos() {
        return txtmos;
    }

    public void setTxtmos(JTextField txtmos) {
        this.txtmos = txtmos;
    }

    public JTextField getTxtmos1() {
        return txtmos1;
    }

    public void setTxtmos1(JTextField txtmos1) {
        this.txtmos1 = txtmos1;
    }


    public JButton getBjnCancelar() {
        return bjnCancelar;
    }

    public void setBjnCancelar(JButton bjnCancelar) {
        this.bjnCancelar = bjnCancelar;
    }

    public JButton getBjnMostrar() {
        return bjnMostrar;
    }

    public void setBjnMostrar(JButton bjnMostrar) {
        this.bjnMostrar = bjnMostrar;
    }

    public JTextField getTxtMostrar() {
        return txtMostrar;
    }

    public void setTxtMostrar(JTextField txtMostrar) {
        this.txtMostrar = txtMostrar;
    }

    public JTextArea getTxtMostrarProducto() {
        return txtMostrarProducto;
    }

    public void setTxtMostrarProducto(JTextArea txtMostrarProducto) {
        this.txtMostrarProducto = txtMostrarProducto;
    }
        public void mostrarMnesaje(String mensaje ){
        
        dispose();
    }
    /**
     * Creates new form BuscarProducto
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrarProducto = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMostrar = new javax.swing.JTextField();
        bjnMostrar = new javax.swing.JButton();
        bjnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtmos = new javax.swing.JTextField();
        txtmos1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        txtMostrarProducto.setColumns(20);
        txtMostrarProducto.setRows(5);
        jScrollPane1.setViewportView(txtMostrarProducto);

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Producto Buscado");

        jLabel2.setText("Ingrese Codigo ");

        bjnMostrar.setBackground(new java.awt.Color(204, 204, 204));
        bjnMostrar.setForeground(new java.awt.Color(0, 204, 204));
        bjnMostrar.setText("Mostrar");
        bjnMostrar.addActionListener(this::bjnMostrarActionPerformed);

        bjnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        bjnCancelar.setForeground(new java.awt.Color(0, 204, 204));
        bjnCancelar.setText("Cancelar");
        bjnCancelar.addActionListener(this::bjnCancelarActionPerformed);

        jLabel3.setText("Precio");

        txtmos.addActionListener(this::txtmosActionPerformed);

        txtmos1.addActionListener(this::txtmos1ActionPerformed);

        jLabel4.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 84, Short.MAX_VALUE)
                .addComponent(bjnMostrar)
                .addGap(44, 44, 44)
                .addComponent(bjnCancelar)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmos1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bjnMostrar)
                    .addComponent(bjnCancelar))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bjnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bjnMostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bjnMostrarActionPerformed

    private void bjnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bjnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bjnCancelarActionPerformed

    private void txtmosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmosActionPerformed

    private void txtmos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmos1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bjnCancelar;
    private javax.swing.JButton bjnMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtMostrar;
    private javax.swing.JTextArea txtMostrarProducto;
    private javax.swing.JTextField txtmos;
    private javax.swing.JTextField txtmos1;
    // End of variables declaration//GEN-END:variables

    public Object getTxtCodigoProducto() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
