/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ec.edu.ups.carrito.views;

import ec.edu.ups.carrito.models.DAo.ProductoDAO;
import ec.edu.ups.carrito.models.DAo.ProductoDaoMemoria;
import ec.edu.ups.carrito.models.controller.ProductoController;

/**
 *
 * @author Usuario
 */
public class PrincipalView extends javax.swing.JFrame {

    private CrearProductoView crearProductoView;
    private ProductoController productoController;
    private BuscarProducto buscarProductoView;
    private EliminarProductoView eliminarProductoView;
    private ActualizarProducto actualizarProductoView;
    private ProductoDAO productoDAO;

    /**
     * Creates new form PrincipalView
     */
    
    
    
    public PrincipalView() {
        initComponents();
        
        crearProductoView = new CrearProductoView();
        productoDAO = new ProductoDaoMemoria();
        buscarProductoView = new BuscarProducto();
        eliminarProductoView = new EliminarProductoView();
        actualizarProductoView = new ActualizarProducto();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        productosMenu = new javax.swing.JMenu();
        MenuItem = new javax.swing.JMenuItem();
        buscarMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        carritoMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        productosMenu.setMnemonic('f');
        productosMenu.setText("Productos");

        MenuItem.setMnemonic('o');
        MenuItem.setText("Crear");
        MenuItem.addActionListener(this::MenuItemActionPerformed);
        productosMenu.add(MenuItem);

        buscarMenuItem.setMnemonic('s');
        buscarMenuItem.setText("Buscar");
        buscarMenuItem.addActionListener(this::buscarMenuItemActionPerformed);
        productosMenu.add(buscarMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Eliminar");
        saveAsMenuItem.addActionListener(this::saveAsMenuItemActionPerformed);
        productosMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Actualizar");
        exitMenuItem.addActionListener(this::exitMenuItemActionPerformed);
        productosMenu.add(exitMenuItem);

        menuBar.add(productosMenu);

        carritoMenu.setMnemonic('e');
        carritoMenu.setText("Carrito");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Agregar");
        carritoMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Eliminar");
        copyMenuItem.addActionListener(this::copyMenuItemActionPerformed);
        carritoMenu.add(copyMenuItem);

        menuBar.add(carritoMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        if (actualizarProductoView == null || !actualizarProductoView.isVisible()) {
        desktopPane.remove(actualizarProductoView);
        desktopPane.add(actualizarProductoView);
        actualizarProductoView.setVisible(true);
    }
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItemActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_copyMenuItemActionPerformed

    private void buscarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMenuItemActionPerformed
        // TODO add your handling code here:
        if (buscarProductoView == null || !buscarProductoView.isVisible()) {
 
            desktopPane.remove(buscarProductoView);
            desktopPane.add(buscarProductoView);
            
            buscarProductoView.setVisible(true);
        }

    }//GEN-LAST:event_buscarMenuItemActionPerformed

    private void MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemActionPerformed
        // TODO add your handling code here:
        if (crearProductoView == null || !crearProductoView.isVisible()) {
           
            desktopPane.remove(crearProductoView);
            crearProductoView.setVisible(true);
            desktopPane.add(crearProductoView);
        }
    }//GEN-LAST:event_MenuItemActionPerformed

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
        // TODO add your handling code here:
        if (eliminarProductoView == null || !eliminarProductoView.isVisible()) {
            desktopPane.remove(eliminarProductoView);
            desktopPane.add(eliminarProductoView);
            eliminarProductoView.setVisible(true);
        }
    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItem;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem buscarMenuItem;
    private javax.swing.JMenu carritoMenu;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu productosMenu;
    private javax.swing.JMenuItem saveAsMenuItem;
    // End of variables declaration//GEN-END:variables

}
