/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ec.edu.ups.carrito.views;

import ec.edu.ups.carrito.controllers.ProductoController;

/**
 *
 * @author Miguel Maza
 */
public class PrincipalView extends javax.swing.JFrame {
    
    
    
    private CrearProductoView crearProductoView ;
    private BuscarProductoView buscarProductoView;
    private ProductoController productoController;
    private EliminarProductoView eliminarProductoView;
    private ActualizarProductoView actualizarProductoView;
    // Cualquier codigo va despues del initComponet ç
    
    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        crearProductoItem = new javax.swing.JMenuItem();
        buscarProductoItem = new javax.swing.JMenuItem();
        eliminarProductoItem = new javax.swing.JMenuItem();
        actualizarProductoMenuItem = new javax.swing.JMenuItem();
        agregarProductoCarrito = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        eliminarProductoCarrito = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Productos");

        crearProductoItem.setMnemonic('o');
        crearProductoItem.setText("Crear");
        crearProductoItem.addActionListener(this::crearProductoItemActionPerformed);
        fileMenu.add(crearProductoItem);

        buscarProductoItem.setMnemonic('s');
        buscarProductoItem.setText("Buscar");
        buscarProductoItem.addActionListener(this::buscarProductoItemActionPerformed);
        fileMenu.add(buscarProductoItem);

        eliminarProductoItem.setMnemonic('a');
        eliminarProductoItem.setText("Eliminar");
        eliminarProductoItem.addActionListener(this::eliminarProductoItemActionPerformed);
        fileMenu.add(eliminarProductoItem);

        actualizarProductoMenuItem.setMnemonic('x');
        actualizarProductoMenuItem.setText("Actualizar");
        actualizarProductoMenuItem.addActionListener(this::actualizarProductoMenuItemActionPerformed);
        fileMenu.add(actualizarProductoMenuItem);

        menuBar.add(fileMenu);

        agregarProductoCarrito.setMnemonic('e');
        agregarProductoCarrito.setText("Carrito");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Agregar");
        cutMenuItem.addActionListener(this::cutMenuItemActionPerformed);
        agregarProductoCarrito.add(cutMenuItem);

        eliminarProductoCarrito.setMnemonic('y');
        eliminarProductoCarrito.setText("Eliminar");
        agregarProductoCarrito.add(eliminarProductoCarrito);

        menuBar.add(agregarProductoCarrito);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarProductoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarProductoMenuItemActionPerformed
                    if ( actualizarProductoView == null || actualizarProductoView.isVisible() )
                    actualizarProductoView = new ActualizarProductoView();
                    productoController = new ProductoController( actualizarProductoView );
                    actualizarProductoView.setVisible(true);
                    desktopPane.add(actualizarProductoView);
    }//GEN-LAST:event_actualizarProductoMenuItemActionPerformed

    private void buscarProductoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProductoItemActionPerformed
                 if (buscarProductoView == null || buscarProductoView.isVisible() )
                    buscarProductoView = new BuscarProductoView();
                    productoController = new ProductoController( buscarProductoView );
                    buscarProductoView.setVisible(true);
                    desktopPane.add(buscarProductoView);
                 
                     // TODO add your handling code here:
    }//GEN-LAST:event_buscarProductoItemActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void crearProductoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearProductoItemActionPerformed
                         // TODO add your handling code here:ç
                if(crearProductoView == null || !crearProductoView.isVisible()){    
                    crearProductoView = new CrearProductoView();
                    productoController = new ProductoController(crearProductoView);
                    crearProductoView.setVisible(true);
                    desktopPane.add(crearProductoView);            
        }
    }//GEN-LAST:event_crearProductoItemActionPerformed

    private void eliminarProductoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProductoItemActionPerformed
       if(eliminarProductoView == null || !eliminarProductoView.isVisible()){    
           eliminarProductoView = new EliminarProductoView();
           productoController = new ProductoController(eliminarProductoView);
           eliminarProductoView.setVisible(true);
           desktopPane.add(eliminarProductoView);            
        } // TODO add your handling code here:
    }//GEN-LAST:event_eliminarProductoItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem actualizarProductoMenuItem;
    private javax.swing.JMenu agregarProductoCarrito;
    private javax.swing.JMenuItem buscarProductoItem;
    private javax.swing.JMenuItem crearProductoItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem eliminarProductoCarrito;
    private javax.swing.JMenuItem eliminarProductoItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
